/**
 * Human player mesh for the YOU (human) side of the split.
 *
 * Art: Minecraft-Steve-style pixel boxes (~1 world unit tall).
 *   Sketchfab lists a free CC-BY Steve by Raph3D, but download needs a login,
 *   so we ship an original boxy Steve GLB (see scripts/genSteveGlb.mjs) plus
 *   an identical procedural fallback. Face / eyes sit on +Z; Crossy camera
 *   sits behind on −Z, so you see the back of the head while hopping up-road.
 *
 * LaneWorld hop actions (same as fly):
 *   0 stay | 1 forward (+Z) | 2 left (+X) | 3 right (−X)
 */

import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

export type HopAction = 0 | 1 | 2 | 3;

/** Yaw so the character faces the hop. Model is oriented to face +Z. */
const YAW_BY_ACTION: Record<HopAction, number | null> = {
  0: null,
  1: 0, // forward → +Z (road ahead; camera sees back of head)
  2: Math.PI / 2, // left → +X
  3: -Math.PI / 2, // right → −X
};

/** Target height in world units — chicken-ish Crossy scale. */
const TARGET_HEIGHT = 1.0;

/** Public URL under Vite `app/public/`. Generated by scripts/genSteveGlb.mjs */
const MODEL_URL = "/models/HumanCharacter.glb";

export type HumanCharacter = THREE.Group & {
  setHopDirection: (action: HopAction) => void;
  /**
   * Call each sync with LaneWorld player X/Z so we can yaw toward the last hop
   * without App or LaneWorld changes.
   */
  updateFacingFromPosition: (x: number, z: number) => void;
};

/**
 * Factory: voxel Steve immediately, then swap in the GLB when load finishes.
 */
export function createHumanCharacter(): HumanCharacter {
  const root = new THREE.Group() as HumanCharacter;
  // Pivot holds either the fallback or the loaded model so we can clear/replace.
  const pivot = new THREE.Group();
  root.add(pivot);

  pivot.add(buildPixelSteve());

  const loader = new GLTFLoader();
  loader.load(
    MODEL_URL,
    (gltf) => {
      const model = gltf.scene;
      fitModelToLane(model);
      while (pivot.children.length) pivot.remove(pivot.children[0]);
      pivot.add(model);
      root.userData.usingGltf = true;
    },
    undefined,
    (err) => {
      console.warn(
        "[HumanCharacter] GLB load failed; using pixel Steve fallback.",
        MODEL_URL,
        err
      );
      root.userData.usingGltf = false;
    }
  );

  // Default: face up the road (+Z). Camera is behind (−Z) → back of head.
  root.rotation.y = 0;
  root.userData.hopAction = 1 as HopAction;
  root.userData.lastX = null as number | null;
  root.userData.lastZ = null as number | null;
  root.userData.usingGltf = false;

  root.setHopDirection = (action: HopAction) => {
    root.userData.hopAction = action;
    const yaw = YAW_BY_ACTION[action];
    if (yaw !== null) root.rotation.y = yaw;
  };

  root.updateFacingFromPosition = (x: number, z: number) => {
    const lastX = root.userData.lastX as number | null;
    const lastZ = root.userData.lastZ as number | null;
    if (lastX !== null && lastZ !== null) {
      const dx = x - lastX;
      const dz = z - lastZ;
      root.setHopDirection(hopActionFromDelta(dx, dz));
    }
    root.userData.lastX = x;
    root.userData.lastZ = z;
  };

  return root;
}

/** Scale so height ≈ TARGET_HEIGHT and feet sit on local y = 0. */
function fitModelToLane(model: THREE.Object3D) {
  model.traverse((obj) => {
    const mesh = obj as THREE.Mesh;
    if (mesh.isMesh) {
      mesh.castShadow = false;
      mesh.receiveShadow = false;
    }
  });

  const box = new THREE.Box3().setFromObject(model);
  const size = new THREE.Vector3();
  box.getSize(size);
  if (size.y < 1e-6) return;

  const scale = TARGET_HEIGHT / size.y;
  model.scale.setScalar(scale);

  box.setFromObject(model);
  model.position.y = -box.min.y;

  // Generated Steve already faces +Z (eyes on +Z). Do NOT add Math.PI —
  // that used to flip KayKit (−Z default) and would turn eyes toward the camera.
  model.rotation.y = 0;
}

/**
 * Same proportions as the GLB: classic 8×32 Minecraft silhouette.
 * Eyes only on +Z so the behind-camera view shows hair / back of head.
 */
function buildPixelSteve(): THREE.Group {
  const g = new THREE.Group();
  const U = 1 / 32;

  const skin = new THREE.MeshLambertMaterial({ color: 0xc68642 });
  const hair = new THREE.MeshLambertMaterial({ color: 0x3b2817 });
  const shirt = new THREE.MeshLambertMaterial({ color: 0x00aaaa });
  const pants = new THREE.MeshLambertMaterial({ color: 0x3d44a5 });
  const shoe = new THREE.MeshLambertMaterial({ color: 0x4a3728 });
  const eyeWhite = new THREE.MeshLambertMaterial({ color: 0xf5f5f5 });
  const eyePupil = new THREE.MeshLambertMaterial({ color: 0x1a1a1a });

  const part = (
    w: number,
    h: number,
    d: number,
    mat: THREE.Material,
    x: number,
    y: number,
    z: number
  ) => {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(w * U, h * U, d * U),
      mat
    );
    mesh.position.set(x * U, (y + h / 2) * U, z * U);
    return mesh;
  };

  g.add(part(4, 12, 4, pants, -2, 0, 0));
  g.add(part(4, 12, 4, pants, 2, 0, 0));
  g.add(part(4, 2, 4, shoe, -2, 0, 0.5));
  g.add(part(4, 2, 4, shoe, 2, 0, 0.5));
  g.add(part(8, 12, 4, shirt, 0, 12, 0));
  g.add(part(4, 12, 4, shirt, -6, 12, 0));
  g.add(part(4, 12, 4, shirt, 6, 12, 0));
  g.add(part(8, 8, 8, skin, 0, 24, 0));
  g.add(part(8.2, 2, 8.2, hair, 0, 30, 0));
  g.add(part(8.2, 6, 1.5, hair, 0, 24, -3.5));
  g.add(part(1.5, 1.5, 0.6, eyeWhite, -2, 28, 4.1));
  g.add(part(1.5, 1.5, 0.6, eyeWhite, 2, 28, 4.1));
  g.add(part(0.8, 1.2, 0.5, eyePupil, -1.7, 27.9, 4.35));
  g.add(part(0.8, 1.2, 0.5, eyePupil, 2.3, 27.9, 4.35));

  return g;
}

/** Infer hop action from a world-space position delta. */
function hopActionFromDelta(dx: number, dz: number): HopAction {
  if (Math.abs(dx) < 1e-6 && Math.abs(dz) < 1e-6) return 0;
  if (Math.abs(dz) >= Math.abs(dx)) return 1;
  return dx > 0 ? 2 : 3;
}
